sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  user: KyleJamesWalker
  password:
    secure: HOvocbDDs9V1JLUsWBrJErSLi0n1tpfaRRGMTdy9KkpmFG4t0y9uKuJQVrEg59gg04WtBr6OxnoerwdFWHM/RozBZcRXxkXM1FB6qsHO51JCivHC3T6mm0Q1fE+CHLJ9oK6HRkooYVyQZtLlf1J5lnwQHrl2JsO8/PwWvuLyv7PkCBzuU1UGI/vXf59jZh9l6Wsg0VFfSJsD+IeS9wXKCf0lPDi10uT6m1IY+rHvT5GYy0JS8lgHhUiFvvSJZri38K+XLT1j+NLrStcH7ILGcN/yXZUmgy6rbtdnyGvymb8n7aN6wZxWsyCFNfxO2JZxC6XtxEafKg1HjBsfgm4lQnJJpXwJnwHz76ynUTa847d7yF2QGJBK0vPTEK5jiFXTAd4hijHJnQazPnbGNd0VZ+aC0yMVoQ4n1GgXAEA8GJT4Abf9DnQw2XuqYQLVCZS9QCNg+uayJymIR+8QXjKCxmNkoz563AESCHKdR1iZbZ+Ephmm0G7/MHLbkyfPjYSm7dB+kCJ/qb1696yJpWrX+ikyn+H98qE+8ZJpEXCbf9kBoK9vzinRLuJIqUMFOxXnLdXUqNQDwzEdYnNnuxNBANAsqfD/cnwMsfeWpiNKOoqmUJyx4zdiCcAofnXcxzVSKmkQ0Gn40pOCLsZkeV61ddWBvFlBlytWptXvHn+sKVs=
  on:
    tags: true
    python: '3.6'
